name: Ping Domains

on:
  push:
    branches:
      - main
  

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

defaults: |
  import numpy as np
    print np.arrange(1,5)
