name: Ping Domains

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ping:
    runs-on: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ping google
        run: |
          class HelloWorld {
            public static void main(String[] args) {
              System.out.println("Hello, World!"); 
            }
              }
