name: Ping Domain Workflow
on:
  push:
    branches:
      - main

jobs:
  ping_domain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y iputils-ping

      - name: Read Domain from File
        id: read_domain
        run: echo "::set-output name=domain::$(www.google.com)"

      - name: Ping Domain
        run: ping -c 5 ${{ steps.read_domain.outputs.domain }}
