name: Ping Domains

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  ping:
    runs-on: windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ping google
        run: |
          while read -r google; do
            ping -c 1 "$google"
          done < google.txt
